config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :inventories
  resources :products
  resources :product_types
  resources :users
  root 'transactions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = filter_transactions
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create

    @transaction = Transaction.new(transaction_params)
   
    if params[:transaction_type] == "buy"
      @transaction.price_per_unity *= -1
    end

    respond_to do |format|
      if @transaction.save
        update_inventory
        format.html { redirect_to @transaction, notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:quantity, :price_per_unity, :product_id, :user_id)
    end

    def update_inventory
      #procurando no inventario o intem vendido
      inventory = Inventory.find_by_product_id(@transaction.product_id)
      if inventory.nil?
        inventory = Inventory.new(product_id: @transaction.product_id, quantity:0)
      end

      if params[:transaction_type]=="buy"
        inventory.quantity += @transaction.quantity
      else
        inventory.quantity -= @transaction.quantity
      end
      inventory.save
    end

    def filter_transactions
      return Transaction.all unless params[:transaction_type].present?
      return Transaction.where('price_per_unity <= 0') if params[:transaction_type]=='buy'
      Transaction.where('price_per_unity > 0')
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :price_per_unity %>
    <%= form.text_field :price_per_unity %>
  </div>

   <div class="field">
    <label>produto</label>
    <select name="transaction[product_id]" style="display:bloack">
      <% Product.all.each do |product| %>
         <option value="<%= product.id %>"><%= product.name %></option>
      <% end %>
    </select>
  </div>

  <div class="field">
    <label>Usuario</label>
    <select name="transaction[user_id]" style="display:bloack">
      <% User.all.each do |user| %>
         <option value="<%= user.id %>"><%= user.name %></option>
      <% end %>
    </select>
  </div>
  
<div class="field">
  <label>Tipo de transação</label>
  <select name="transaction_type" style="display:bloack">
    <option value="buy">Compra</option>
     <option value="sell">venda</option>
  </select>
</div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transações</h1>

<table>
  <thead>
    <tr>
      <th>Quantidade</th>
      <th>Preço</th>
      <th>Produto</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.quantity %></td>
        <td><%= transaction.price_per_unity %></td>
        <td><%= transaction.product.name %> - <%= transaction.product.product_type.name %></td>
        <td><%= transaction.user.name %></td>
         <td><%= transaction.created_at.strftime("%d/%m/%Y - %H:%M")%></td>
        <td><%= link_to 'Mostra', transaction %></td>
        <td><%= link_to 'Editar', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Deletar', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div>
  <%= link_to 'Nova trasação', new_transaction_path %>
</div>
<div>
  <%= link_to 'Inventario', inventories_path %>
</div>

<div>
  <%= link_to 'Produtos', products_path %>
</div>

<!--<%= link_to 'Compras', transaction_path("?trasaction_type=buy")%> -->

app/views/transactions/new.html.erb
<h1>Nova transação</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @transaction.quantity %>
</p>

<p>
  <strong>Price per unity:</strong>
  <%= @transaction.price_per_unity %>
</p>

<p>
  <strong>Product:</strong>
  <%= @transaction.product_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @transaction.user_id %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>